//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class AcceptCookies:public drogon::DrTemplate<AcceptCookies>
{
public:
	AcceptCookies(){};
	virtual ~AcceptCookies(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
