//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "AcceptCookies.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string AcceptCookies::genText(const DrTemplateData& AcceptCookies_view_data)
{
	drogon::OStringStream AcceptCookies_tmp_stream;
	std::string layoutName{""};
	AcceptCookies_tmp_stream << "<!DOCTYPE html>\n";
	AcceptCookies_tmp_stream << "<html>\n";
	AcceptCookies_tmp_stream << "<head>\n";
	AcceptCookies_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	AcceptCookies_tmp_stream << "    <title>Accept Cookies Agrement</title>\n";
	AcceptCookies_tmp_stream << "</head>\n";
	AcceptCookies_tmp_stream << "<body>\n";
	AcceptCookies_tmp_stream << "  <form action=\"/landing_page\" method=\"post\">\n";
	AcceptCookies_tmp_stream << "		<div class=\"container\">\n";
	AcceptCookies_tmp_stream << "			<button type=\"submit\">Accept</button>\n";
	AcceptCookies_tmp_stream << "		</div>\n";
	AcceptCookies_tmp_stream << "  </form> \n";
AcceptCookies_tmp_stream<<"\n";
	AcceptCookies_tmp_stream << "</body>\n";
	AcceptCookies_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(AcceptCookies_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = AcceptCookies_view_data;
auto str = std::move(AcceptCookies_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
