//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "FAQ.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string FAQ::genText(const DrTemplateData& FAQ_view_data)
{
	drogon::OStringStream FAQ_tmp_stream;
	std::string layoutName{""};
	FAQ_tmp_stream << "<!DOCTYPE html>\n";
	FAQ_tmp_stream << "<html lang=\"en\">\n";
	FAQ_tmp_stream << "  <head>\n";
	FAQ_tmp_stream << "      <meta charset=\"utf-8\">\n";
	FAQ_tmp_stream << "      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
	FAQ_tmp_stream << "      <meta name=\"description\" content=\"Check out our tiny URL pricing.\">\n";
	FAQ_tmp_stream << "      <title>Here is our tiny URL pricing</title>\n";
	FAQ_tmp_stream << "      <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\n";
	FAQ_tmp_stream << "  </head>\n";
	FAQ_tmp_stream << "  <body>\n";
	FAQ_tmp_stream << "    ";
{
    auto templ=DrTemplateBase::newTemplate("Header.csp");
    if(templ){
      FAQ_tmp_stream<< templ->genText(FAQ_view_data);
    }
}
FAQ_tmp_stream<<"\n";
	FAQ_tmp_stream << "<div class=\"pricing-header p-3 pb-md-4 mx-auto text-center\">\n";
	FAQ_tmp_stream << "      <h1 class=\"display-4 fw-normal text-body-emphasis\">Pricing</h1>\n";
	FAQ_tmp_stream << "      <p class=\"fs-5 text-body-secondary\">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>\n";
	FAQ_tmp_stream << "</div>\n";
	FAQ_tmp_stream << "<div class=\"container py-3\">\n";
	FAQ_tmp_stream << "<main>\n";
	FAQ_tmp_stream << "    <div class=\"row row-cols-1 row-cols-md-3 mb-3 text-center\">\n";
	FAQ_tmp_stream << "      <div class=\"col\">\n";
	FAQ_tmp_stream << "        <div class=\"card mb-4 rounded-3 shadow-sm\">\n";
	FAQ_tmp_stream << "          <div class=\"card-header py-3\">\n";
	FAQ_tmp_stream << "            <h4 class=\"my-0 fw-normal\">Free</h4>\n";
	FAQ_tmp_stream << "          </div>\n";
	FAQ_tmp_stream << "          <div class=\"card-body\">\n";
	FAQ_tmp_stream << "            <h1 class=\"card-title pricing-card-title\">$0<small class=\"text-body-secondary fw-light\">/mo</small></h1>\n";
	FAQ_tmp_stream << "            <ul class=\"list-unstyled mt-3 mb-4\">\n";
	FAQ_tmp_stream << "              <li>10 users included</li>\n";
	FAQ_tmp_stream << "              <li>2 GB of storage</li>\n";
	FAQ_tmp_stream << "              <li>Email support</li>\n";
	FAQ_tmp_stream << "              <li>Help center access</li>\n";
	FAQ_tmp_stream << "            </ul>\n";
	FAQ_tmp_stream << "            <button type=\"button\" class=\"w-100 btn btn-lg btn-outline-primary\">Sign up for free</button>\n";
	FAQ_tmp_stream << "          </div>\n";
	FAQ_tmp_stream << "        </div>\n";
	FAQ_tmp_stream << "      </div>\n";
	FAQ_tmp_stream << "      <div class=\"col\">\n";
	FAQ_tmp_stream << "        <div class=\"card mb-4 rounded-3 shadow-sm\">\n";
	FAQ_tmp_stream << "          <div class=\"card-header py-3\">\n";
	FAQ_tmp_stream << "            <h4 class=\"my-0 fw-normal\">Pro</h4>\n";
	FAQ_tmp_stream << "          </div>\n";
	FAQ_tmp_stream << "          <div class=\"card-body\">\n";
	FAQ_tmp_stream << "            <h1 class=\"card-title pricing-card-title\">$15<small class=\"text-body-secondary fw-light\">/mo</small></h1>\n";
	FAQ_tmp_stream << "            <ul class=\"list-unstyled mt-3 mb-4\">\n";
	FAQ_tmp_stream << "              <li>20 users included</li>\n";
	FAQ_tmp_stream << "              <li>10 GB of storage</li>\n";
	FAQ_tmp_stream << "              <li>Priority email support</li>\n";
	FAQ_tmp_stream << "              <li>Help center access</li>\n";
	FAQ_tmp_stream << "            </ul>\n";
	FAQ_tmp_stream << "            <button type=\"button\" class=\"w-100 btn btn-lg btn-primary\">Get started</button>\n";
	FAQ_tmp_stream << "          </div>\n";
	FAQ_tmp_stream << "        </div>\n";
	FAQ_tmp_stream << "      </div>\n";
	FAQ_tmp_stream << "      <div class=\"col\">\n";
	FAQ_tmp_stream << "        <div class=\"card mb-4 rounded-3 shadow-sm border-primary\">\n";
	FAQ_tmp_stream << "          <div class=\"card-header py-3 text-bg-primary border-primary\">\n";
	FAQ_tmp_stream << "            <h4 class=\"my-0 fw-normal\">Enterprise</h4>\n";
	FAQ_tmp_stream << "          </div>\n";
	FAQ_tmp_stream << "          <div class=\"card-body\">\n";
	FAQ_tmp_stream << "            <h1 class=\"card-title pricing-card-title\">$29<small class=\"text-body-secondary fw-light\">/mo</small></h1>\n";
	FAQ_tmp_stream << "            <ul class=\"list-unstyled mt-3 mb-4\">\n";
	FAQ_tmp_stream << "              <li>30 users included</li>\n";
	FAQ_tmp_stream << "              <li>15 GB of storage</li>\n";
	FAQ_tmp_stream << "              <li>Phone and email support</li>\n";
	FAQ_tmp_stream << "              <li>Help center access</li>\n";
	FAQ_tmp_stream << "            </ul>\n";
	FAQ_tmp_stream << "            <button type=\"button\" class=\"w-100 btn btn-lg btn-primary\">Contact us</button>\n";
	FAQ_tmp_stream << "          </div>\n";
	FAQ_tmp_stream << "        </div>\n";
	FAQ_tmp_stream << "      </div>\n";
	FAQ_tmp_stream << "    </div>\n";
FAQ_tmp_stream<<"\n";
	FAQ_tmp_stream << "    <h2 class=\"display-6 text-center mb-4\">Compare plans</h2>\n";
FAQ_tmp_stream<<"\n";
	FAQ_tmp_stream << "    <div class=\"table-responsive\">\n";
	FAQ_tmp_stream << "      <table class=\"table text-center\">\n";
	FAQ_tmp_stream << "        <thead>\n";
	FAQ_tmp_stream << "          <tr>\n";
	FAQ_tmp_stream << "            <th style=\"width: 34%;\"></th>\n";
	FAQ_tmp_stream << "            <th style=\"width: 22%;\">Free</th>\n";
	FAQ_tmp_stream << "            <th style=\"width: 22%;\">Pro</th>\n";
	FAQ_tmp_stream << "            <th style=\"width: 22%;\">Enterprise</th>\n";
	FAQ_tmp_stream << "          </tr>\n";
	FAQ_tmp_stream << "        </thead>\n";
	FAQ_tmp_stream << "        <tbody>\n";
	FAQ_tmp_stream << "          <tr>\n";
	FAQ_tmp_stream << "            <th scope=\"row\" class=\"text-start\">Public</th>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "          </tr>\n";
	FAQ_tmp_stream << "          <tr>\n";
	FAQ_tmp_stream << "            <th scope=\"row\" class=\"text-start\">Private</th>\n";
	FAQ_tmp_stream << "            <td></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "          </tr>\n";
	FAQ_tmp_stream << "        </tbody>\n";
FAQ_tmp_stream<<"\n";
	FAQ_tmp_stream << "        <tbody>\n";
	FAQ_tmp_stream << "          <tr>\n";
	FAQ_tmp_stream << "            <th scope=\"row\" class=\"text-start\">Permissions</th>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "          </tr>\n";
	FAQ_tmp_stream << "          <tr>\n";
	FAQ_tmp_stream << "            <th scope=\"row\" class=\"text-start\">Sharing</th>\n";
	FAQ_tmp_stream << "            <td></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "          </tr>\n";
	FAQ_tmp_stream << "          <tr>\n";
	FAQ_tmp_stream << "            <th scope=\"row\" class=\"text-start\">Unlimited members</th>\n";
	FAQ_tmp_stream << "            <td></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "          </tr>\n";
	FAQ_tmp_stream << "          <tr>\n";
	FAQ_tmp_stream << "            <th scope=\"row\" class=\"text-start\">Extra security</th>\n";
	FAQ_tmp_stream << "            <td></td>\n";
	FAQ_tmp_stream << "            <td></td>\n";
	FAQ_tmp_stream << "            <td><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#check\"></use></svg></td>\n";
	FAQ_tmp_stream << "          </tr>\n";
	FAQ_tmp_stream << "        </tbody>\n";
	FAQ_tmp_stream << "      </table>\n";
	FAQ_tmp_stream << "    </div>\n";
	FAQ_tmp_stream << "</main>\n";
	FAQ_tmp_stream << "</div>\n";
	FAQ_tmp_stream << "    ";
{
    auto templ=DrTemplateBase::newTemplate("Footer.csp");
    if(templ){
      FAQ_tmp_stream<< templ->genText(FAQ_view_data);
    }
}
FAQ_tmp_stream<<"\n";
	FAQ_tmp_stream << "  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\n";
	FAQ_tmp_stream << "  </body>\n";
	FAQ_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(FAQ_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = FAQ_view_data;
auto str = std::move(FAQ_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
