//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class FAQ:public drogon::DrTemplate<FAQ>
{
public:
	FAQ(){};
	virtual ~FAQ(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
