//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Features:public drogon::DrTemplate<Features>
{
public:
	Features(){};
	virtual ~Features(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
