//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Footer:public drogon::DrTemplate<Footer>
{
public:
	Footer(){};
	virtual ~Footer(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
