//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Footer.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string Footer::genText(const DrTemplateData& Footer_view_data)
{
	drogon::OStringStream Footer_tmp_stream;
	std::string layoutName{""};
	Footer_tmp_stream << "    <div class=\"container\">\n";
	Footer_tmp_stream << "  <footer class=\"py-5\">\n";
	Footer_tmp_stream << "    <div class=\"row\">\n";
	Footer_tmp_stream << "      <div class=\"col-2\">\n";
	Footer_tmp_stream << "        <h5>Section</h5>\n";
	Footer_tmp_stream << "        <ul class=\"nav flex-column\">\n";
	Footer_tmp_stream << "          <li class=\"nav-item mb-2\"><a href=\"#\" class=\"nav-link p-0 text-muted\">Home</a></li>\n";
	Footer_tmp_stream << "          <li class=\"nav-item mb-2\"><a href=\"#\" class=\"nav-link p-0 text-muted\">Features</a></li>\n";
	Footer_tmp_stream << "          <li class=\"nav-item mb-2\"><a href=\"#\" class=\"nav-link p-0 text-muted\">Pricing</a></li>\n";
	Footer_tmp_stream << "          <li class=\"nav-item mb-2\"><a href=\"#\" class=\"nav-link p-0 text-muted\">FAQs</a></li>\n";
	Footer_tmp_stream << "          <li class=\"nav-item mb-2\"><a href=\"#\" class=\"nav-link p-0 text-muted\">About</a></li>\n";
	Footer_tmp_stream << "        </ul>\n";
	Footer_tmp_stream << "      </div>\n";
	Footer_tmp_stream << "      <div class=\"col-2\">\n";
	Footer_tmp_stream << "      </div>\n";
	Footer_tmp_stream << "      <div class=\"col-2\">\n";
	Footer_tmp_stream << "      </div>\n";
	Footer_tmp_stream << "  \n";
	Footer_tmp_stream << "      <div class=\"col-4 offset-1\">\n";
	Footer_tmp_stream << "        <form >\n";
	Footer_tmp_stream << "          <h5>Subscribe to our newsletter</h5>\n";
	Footer_tmp_stream << "          <p>Monthly digest of whats new and exciting from us.</p>\n";
	Footer_tmp_stream << "          <div class=\"d-flex w-100 gap-2\">\n";
	Footer_tmp_stream << "            <label for=\"newsletter1\" class=\"visually-hidden\">Email address</label>\n";
	Footer_tmp_stream << "            <input id=\"newsletter1\" type=\"text\" class=\"form-control\" placeholder=\"Email address\" control-id=\"ControlID-1\">\n";
	Footer_tmp_stream << "            <button class=\"btn btn-primary\" type=\"button\" control-id=\"ControlID-2\">Subscribe</button>\n";
	Footer_tmp_stream << "          </div>\n";
	Footer_tmp_stream << "        </form>\n";
	Footer_tmp_stream << "      </div>\n";
	Footer_tmp_stream << "    </div>\n";
Footer_tmp_stream<<"\n";
	Footer_tmp_stream << "    <div class=\"d-flex justify-content-between py-4 my-4 border-top\">\n";
	Footer_tmp_stream << "      <p>© 2024 Company, Inc. All rights reserved.</p>\n";
	Footer_tmp_stream << "      <ul class=\"list-unstyled d-flex\">\n";
	Footer_tmp_stream << "        <li class=\"ms-3\"><a class=\"link-dark\" href=\"#\"><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#twitter\"></use></svg></a></li>\n";
	Footer_tmp_stream << "        <li class=\"ms-3\"><a class=\"link-dark\" href=\"#\"><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#instagram\"></use></svg></a></li>\n";
	Footer_tmp_stream << "        <li class=\"ms-3\"><a class=\"link-dark\" href=\"#\"><svg class=\"bi\" width=\"24\" height=\"24\"><use xlink:href=\"#facebook\"></use></svg></a></li>\n";
	Footer_tmp_stream << "      </ul>\n";
	Footer_tmp_stream << "    </div>\n";
	Footer_tmp_stream << "  </footer>\n";
	Footer_tmp_stream << "</div>\n";
if(layoutName.empty())
{
std::string ret{std::move(Footer_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Footer_view_data;
auto str = std::move(Footer_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
