//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Pricing.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string Pricing::genText(const DrTemplateData& Pricing_view_data)
{
	drogon::OStringStream Pricing_tmp_stream;
	std::string layoutName{""};
	Pricing_tmp_stream << "<!DOCTYPE html>\n";
	Pricing_tmp_stream << "<html lang=\"en\">\n";
	Pricing_tmp_stream << "  <head>\n";
	Pricing_tmp_stream << "      <meta charset=\"utf-8\">\n";
	Pricing_tmp_stream << "      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
	Pricing_tmp_stream << "      <meta name=\"description\" content=\"This is an example website.\">\n";
	Pricing_tmp_stream << "	  <title>Welcome to our website fellow internet browser</title>\n";
	Pricing_tmp_stream << "	  \n";
	Pricing_tmp_stream << "	          <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\n";
	Pricing_tmp_stream << "		    </head>\n";
	Pricing_tmp_stream << "  <body>\n";
	Pricing_tmp_stream << "    ";
{
    auto templ=DrTemplateBase::newTemplate("Header.csp");
    if(templ){
      Pricing_tmp_stream<< templ->genText(Pricing_view_data);
    }
}
Pricing_tmp_stream<<"\n";
	Pricing_tmp_stream << "    <div class=\"container my-5\" >\n";
	Pricing_tmp_stream << "    <div class=\"p-5 text-center bg-body-tertiary rounded-3\">\n";
	Pricing_tmp_stream << "    <svg class=\"bi mt-4 mb-3\" style=\"color: var(--bs-indigo);\" width=\"100\" height=\"100\"><use xlink:href=\"#bootstrap\"></use></svg>\n";
	Pricing_tmp_stream << "    <h1 class=\"text-body-emphasis\">Jumbotron with icon</h1>\n";
	Pricing_tmp_stream << "    <p class=\"col-lg-8 mx-auto fs-5 text-muted\">\n";
	Pricing_tmp_stream << "      This is a custom jumbotron featuring an SVG image at the top, some longer text that wraps early thanks to a responsive <code>.col-*</code> class, and a customized call to action.\n";
	Pricing_tmp_stream << "    </p>\n";
	Pricing_tmp_stream << "    <div class=\"d-inline-flex gap-2 mb-5\">\n";
	Pricing_tmp_stream << "      <button class=\"d-inline-flex align-items-center btn btn-primary btn-lg px-4 rounded-pill\" type=\"button\">\n";
	Pricing_tmp_stream << "        Call to action\n";
	Pricing_tmp_stream << "        <svg class=\"bi ms-2\" width=\"24\" height=\"24\"><use xlink:href=\"#arrow-right-short\"></use></svg>\n";
	Pricing_tmp_stream << "      </button>\n";
	Pricing_tmp_stream << "      <button class=\"btn btn-outline-secondary btn-lg px-4 rounded-pill\" type=\"button\">\n";
	Pricing_tmp_stream << "        Secondary link\n";
	Pricing_tmp_stream << "      </button>\n";
	Pricing_tmp_stream << "    </div>\n";
	Pricing_tmp_stream << "  </div>\n";
	Pricing_tmp_stream << "    </div>\n";
Pricing_tmp_stream<<"\n";
{
    auto templ=DrTemplateBase::newTemplate("Footer.csp");
    if(templ){
      Pricing_tmp_stream<< templ->genText(Pricing_view_data);
    }
}
Pricing_tmp_stream<<"\n";
Pricing_tmp_stream<<"\n";
	Pricing_tmp_stream << "      <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\n";
	Pricing_tmp_stream << "</body>\n";
	Pricing_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(Pricing_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Pricing_view_data;
auto str = std::move(Pricing_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
